# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

title: Guzel Ishmaeva
first_name: Guzel
last_name: Ishmaeva
contact_note: >
  Fifth-year Ph.D. Candidate in Economics at New York University.
description: >
  Research in empirical industrial organization, applied microeconomics, and media economics.
footer_text: >
  © 2025 Guzel Ishmaeva · Powered by <a href="https://jekyllrb.com/" target="_blank">Jekyll</a>
  with <a href="https://github.com/alshedivat/al-folio">al-folio</a> theme ·
  Hosted by <a href="https://pages.github.com/" target="_blank">GitHub Pages</a>
keywords: economics, empirical IO, industrial organization, media
lang: en
icon: 🎓

# IMPORTANT: for preview site
url: "https://guzelishmaeva.github.io"
baseurl: "/alfolio-preview"

back_to_top: true

# -----------------------------------------------------------------------------
# Author / Socials
# -----------------------------------------------------------------------------

author:
  name: "Guzel Ishmaeva"
  email: "gvi2002@nyu.edu"
  linkedin: "guzelishmaeva"
  cv: "assets/pdf/CV.pdf"   # put your CV here
  avatar: "assets/img/avatar.jpg"
  bio: "Sixth-year Ph.D. Candidate in Economics at New York University. Research in empirical IO, applied micro, and media economics."

# -----------------------------------------------------------------------------
# Features
# -----------------------------------------------------------------------------

enable_darkmode: true
enable_navbar_social: true
enable_project_categories: true
enable_masonry: true
enable_math: true
enable_progressbar: true

# -----------------------------------------------------------------------------
# Disable unused collections/blog
# -----------------------------------------------------------------------------

collections: {}
blog_name: 
blog_description:

# -----------------------------------------------------------------------------
# Minimal third-party libraries (must exist for build to pass)
# -----------------------------------------------------------------------------

third_party_libraries:
  download: false
  bootstrap-table:
    version: "1.22.4"
    url:
      css: "https://cdn.jsdelivr.net/npm/bootstrap-table@{{version}}/dist/bootstrap-table.min.css"
      js: "https://cdn.jsdelivr.net/npm/bootstrap-table@{{version}}/dist/bootstrap-table.min.js"
  chartjs:
    version: "4.4.1"
    url:
      js: "https://cdn.jsdelivr.net/npm/chart.js@{{version}}/dist/chart.umd.min.js"

