# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

title: Guzel Ishmaeva
first_name: Guzel
middle_name:
last_name: Ishmaeva
contact_note: >
  Sixth-year Ph.D. Candidate in Economics at New York University.
description: > # the ">" symbol means to ignore newlines until "footer_text:"
  Research in empirical industrial organization, applied microeconomics, and media economics.
footer_text: >
  © 2025 Guzel Ishmaeva · Powered by <a href="https://jekyllrb.com/" target="_blank">Jekyll</a>
  with <a href="https://github.com/alshedivat/al-folio">al-folio</a> theme ·
  Hosted by <a href="https://pages.github.com/" target="_blank">GitHub Pages</a>.
keywords: economics, empirical IO, industrial organization, media
lang: en
icon: 🎓

url: https://guzelishmaeva.github.io
baseurl: /alfolio-preview
last_updated: false
back_to_top: true

# -----------------------------------------------------------------------------
# Theme
# -----------------------------------------------------------------------------

navbar_fixed: true
footer_fixed: true
search_enabled: false
socials_in_search: false
posts_in_search: false
bib_search: false

# Dimensions
max_width: 930px

# -----------------------------------------------------------------------------
# Author / Socials
# -----------------------------------------------------------------------------

author:
  name: "Guzel Ishmaeva"
  avatar: "assets/img/avatar.jpg"
  bio: "Ph.D. Candidate in Economics at New York University"
  email: "gvi2002@nyu.edu"
  linkedin: "guzelishmaeva"
  cv: "assets/pdf/CV.pdf"

# -----------------------------------------------------------------------------
# Blog (disabled)
# -----------------------------------------------------------------------------

blog_name:
blog_description:
permalink: /blog/:year/:title/

pagination:
  enabled: false

related_blog_posts:
  enabled: false

# -----------------------------------------------------------------------------
# Newsletter (disabled)
# -----------------------------------------------------------------------------

newsletter:
  enabled: false

# -----------------------------------------------------------------------------
# Collections (disabled unless you add later)
# -----------------------------------------------------------------------------

collections: {}

# -----------------------------------------------------------------------------
# Jekyll Scholar (disabled)
# -----------------------------------------------------------------------------

scholar:
  last_name: [Ishmaeva]
  first_name: [Guzel]
  source: /_bibliography/
  bibliography: none.bib
  query: ""

# -----------------------------------------------------------------------------
# Features
# -----------------------------------------------------------------------------

enable_darkmode: true
enable_navbar_social: true
enable_project_categories: true
enable_masonry: true
enable_math: true
enable_progressbar: true

# -----------------------------------------------------------------------------
# Third-party libraries (must exist)
# -----------------------------------------------------------------------------

third_party_libraries:
  download: false
  bootstrap-table:
    version: "1.22.4"
    url:
      css: "https://cdn.jsdelivr.net/npm/bootstrap-table@{{version}}/dist/bootstrap-table.min.css"
      js: "https://cdn.jsdelivr.net/npm/bootstrap-table@{{version}}/dist/bootstrap-table.min.js"
  chartjs:
    version: "4.4.1"
    url:
      js: "https://cdn.jsdelivr.net/npm/chart.js@{{version}}/dist/chart.umd.min.js"


